package main

import (
	"fmt"
	"os"
)

// ExportSVG exports the string art to SVG format
func ExportSVG(lines []Line, config *Config, outputPath string) error {
	// SVG dimensions: 600mm x 600mm
	const svgWidth = 600.0
	const svgHeight = 600.0
	const strokeWidth = 0.18 // mm

	// Calculate pin positions
	centerX, centerY := svgWidth/2, svgHeight/2
	radius := (svgWidth / 2) - 10
	pins := GeneratePins(config.NumPins, radius, centerX, centerY)

	// Create SVG file
	file, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer file.Close()

	// Write SVG header
	fmt.Fprintf(file, `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" 
     width="600mm" 
     height="600mm" 
     viewBox="0 0 600 600">
  <title>String Art Generated by Go Implementation</title>
  <desc>Generated with %d pins and %d lines</desc>
  
  <!-- Background -->
  <rect width="600" height="600" fill="white"/>
  
  <!-- String lines -->
  <g id="strings" stroke="black" stroke-width="%.2f" stroke-opacity="1.0" fill="none">
`, config.NumPins, len(lines), strokeWidth)

	// Write lines
	for _, line := range lines {
		from := pins[line.From]
		to := pins[line.To]
		fmt.Fprintf(file, `    <line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f"/>
`, from.X, from.Y, to.X, to.Y)
	}

	// Write pins (optional, for visualization)
	fmt.Fprintf(file, `  </g>
  
  <!-- Pins (for reference) -->
  <g id="pins" fill="red" opacity="0.3">
`)

	for _, pin := range pins {
		fmt.Fprintf(file, `    <circle cx="%.2f" cy="%.2f" r="1"/>
`, pin.X, pin.Y)
	}

	// Close SVG
	fmt.Fprintf(file, `  </g>
</svg>
`)

	return nil
}

// ExportSVGDual exports dual-color string art to SVG format
func ExportSVGDual(blackLines, whiteLines []Line, config *Config, outputPath string) error {
	// SVG dimensions: 600mm x 600mm
	const svgWidth = 600.0
	const svgHeight = 600.0
	const strokeWidth = 0.18 // mm

	// Calculate pin positions
	centerX, centerY := svgWidth/2, svgHeight/2
	radius := (svgWidth / 2) - 10
	pins := GeneratePins(config.NumPins, radius, centerX, centerY)

	// Create SVG file
	file, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer file.Close()

	// Write SVG header
	fmt.Fprintf(file, `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" 
     width="600mm" 
     height="600mm" 
     viewBox="0 0 600 600">
  <title>Dual-Color String Art Generated by Go Implementation</title>
  <desc>Generated with %d pins, %d black lines, %d white lines</desc>
  
  <!-- Background (transparent for dual-color) -->
  <rect width="600" height="600" fill="white" fill-opacity="0.5"/>
  
  <!-- Black string lines -->
  <g id="black-strings" stroke="black" stroke-width="%.2f" stroke-opacity="1.0" fill="none">
`, config.NumPins, len(blackLines), len(whiteLines), strokeWidth)

	// Write black lines
	for _, line := range blackLines {
		from := pins[line.From]
		to := pins[line.To]
		fmt.Fprintf(file, `    <line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f"/>
`, from.X, from.Y, to.X, to.Y)
	}

	fmt.Fprintf(file, `  </g>
  
  <!-- White string lines -->
  <g id="white-strings" stroke="white" stroke-width="%.2f" stroke-opacity="1.0" fill="none">
`, strokeWidth)

	// Write white lines
	for _, line := range whiteLines {
		from := pins[line.From]
		to := pins[line.To]
		fmt.Fprintf(file, `    <line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f"/>
`, from.X, from.Y, to.X, to.Y)
	}

	// Write pins (optional, for visualization)
	fmt.Fprintf(file, `  </g>
  
  <!-- Pins (for reference) -->
  <g id="pins" fill="red" opacity="0.3">
`)

	for _, pin := range pins {
		fmt.Fprintf(file, `    <circle cx="%.2f" cy="%.2f" r="1"/>
`, pin.X, pin.Y)
	}

	// Close SVG
	fmt.Fprintf(file, `  </g>
</svg>
`)

	return nil
}
